name: freesg
services:
  db:
    image: postgres:17.2-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database

  pgadmin:
    image: dpage/pgadmin4:9
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    depends_on:
      - db

  proxy:
    image: nginx:1.27.2-alpine
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - './.nginx/nginx.conf:/etc/nginx/nginx.conf:ro'



