name: recruiter
services:
  db:
    image: postgres:17.2-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database

  proxy:
    image: nginx:1.27.2-alpine
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - '.nginx/nginx.conf:/etc/nginx/nginx.conf:ro'

